[package]
name = "spi-st7789-rpi-zero-w"
version = "0.1.0"
edition = "2021"

[dependencies]
mipidsi = { path = "../../" }
embedded-graphics = "0.8.0"
rppal = { version = "0.17.1", features = ["hal"] }
embedded-hal-bus = "0.2.0"
embedded-hal = "1.0.0"

[workspace]
